apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blueeconomy-platform
resources:
- namespace.yaml
- caddy.yaml
- apisix.yaml
- keycloak.yaml
- opa.yaml
- network-policy.yaml
commonLabels:
  app.kubernetes.io/part-of: blueeconomy-platform
  security.blueeconomy.ng/baseline: restricted
