apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: {name: keycloak-runtime-secrets}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: ministry-production-secrets}
  target: {name: keycloak-runtime-secrets, creationPolicy: Owner}
  data:
  - secretKey: KC_DB_PASSWORD
    remoteRef: {key: blueeconomy/production/keycloak, property: db_password}
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef: {key: blueeconomy/production/keycloak, property: bootstrap_admin_password}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: {name: apisix-runtime-secrets}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: ministry-production-secrets}
  target: {name: apisix-runtime-secrets, creationPolicy: Owner}
  data:
  - secretKey: APISIX_OIDC_CLIENT_SECRET
    remoteRef: {key: blueeconomy/production/apisix, property: oidc_client_secret}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: {name: caddy-tls-material}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: ministry-production-secrets}
  target: {name: caddy-tls-material, creationPolicy: Owner}
  dataFrom:
  - extract: {key: blueeconomy/production/caddy-tls}
